language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then python bin/use2to3; cd py3k-sympy; fi
  - python setup.py install
script:
  # We change directories to make sure that python won't find the copy
  # of sympy in the source directory.
  - mkdir empty
  - cd empty
  - "echo -e \"from sympy.utilities.runtests import run_all_tests\\nif not run_all_tests(): raise Exception('Tests failed')\" | python"
notifications:
  email: false
